apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-restaurant-app-deploy
  labels:
    app: restaurant-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: restaurant-app
  template:
    metadata:
      labels:
        app: restaurant-app
    spec:
      containers:
      - name: simple-restaurant-app-container
        image: dineshsai14211/simple-restaurant-app-img:35
        ports:
        - containerPort: 5000