apiVersion: v1
kind: Service
metadata:
  name: simple-restaurant-app-service
  namespace: default
  labels:
    app: restaurant-app
spec:
  selector:
    app: restaurant-app
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: LoadBalancer
